name: Triggered by API
on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run a command
        run: echo "GitHub Action triggered from GPT!"
